policies:
  - name: KerasPolicy
    epochs: 350
    max_history: 2
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 2
  - name: FormPolicy
