version: '2' 

services:
  bot:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    environment:
      - TELEGRAM_ACCESS_TOKEN
      - TELEGRAM_BOT_NAME
      - TELEGRAM_WEBHOOK_URL
    volumes:
      - ./bot/:/bot/
    ports:
      - 5005:5005
      - 5002:5002
    depends_on:
      - actions
    command: "make run"

  actions:
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    environment:
      - JENA_URL
    ports:
      - 5055:5055
    volumes:
      - ./bot/actions.py:/bot/actions.py
      - ./bot/middleware.py:/bot/middleware.py
      - ./bot/Makefile:/bot/Makefile
    command: "make run-actions"
