version: '2' 

services:
####################################### CHATBOT ###############################
  bot:
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    environment:
      - TELEGRAM_ACCESS_TOKEN
      - TELEGRAM_BOT_NAME
      - TELEGRAM_WEBHOOK_URL
    volumes:
      - ./bot/:/bot/
    ports:
      - 5005:5005
      - 5002:5002
    depends_on:
      - actions
    command: "make run"

  actions:
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    environment:
      - JENA_URL
    ports:
      - 5055:5055
    volumes:
      - ./bot/actions.py:/bot/actions.py
      - ./bot/middleware.py:/bot/middleware.py
      - ./bot/Makefile:/bot/Makefile
    command: "make run-actions"

####################################### TRIPLE STORAGE ########################
  virtuoso:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    volumes:
      - ./data/virtuoso:/data
    ports:
      - "8890:8890"

####################################### JENA API ##############################
  jena:
    image: stain/jena-fuseki
    volumes:
      - ./fuseki:/fuseki
    ports:
      - "3030:3030"
